# -*- coding: utf-8 -*-
"""hf_transformers_train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K15IQ741CoK_KcFekp4q_Co0X77i68Vi

####Mounting Drive for file access/storage
"""

from google.colab import drive
drive.mount('/content/gdrive')

"""####Copy training data and transformers into working directory"""

!cp -r /content/gdrive/My\ Drive/School/FYP\ -\ Niall\ Dillane/data .
!cp -r /content/gdrive/My\ Drive/School/FYP\ -\ Niall\ Dillane/transformers .

!pip install transformers
!pip install tensorflow
!pip install torch torchvision

"""####Train Model"""

!rm -rf output/checkpoint-40000

!python transformers/examples/run_language_modeling.py \
    --output_dir=output \
    --model_type=gpt2 \
    --model_name_or_path=gpt2 \
    --should_continue \
    --do_train \
    --train_data_file=data/ns_over_400_train.txt \
    --do_eval \
    --eval_data_file=data/ns_over_400_test.txt \
    --overwrite_output_dir\
    --block_size=200\
    --per_gpu_train_batch_size=1\
    --save_steps 10000\
    --num_train_epochs=2

!cp -r /content/output/output /content/gdrive/My\ Drive/School/FYP\ -\ Niall\ Dillane/data

"""####Test generation"""

!python transformers/examples/run_generation.py \
    --model_type=gpt2 \
    --model_name_or_path=gpt2 \
    --length=50 \
    --temperature=0.8